apiVersion: apps/v1

kind: Deployment

metadata:

  name: employee-portal-backend

  namespace: employee-portal

  labels:

    app: employee-portal-backend

spec:

  replicas: 2

  selector:

    matchLabels:

      app: employee-portal-backend

  strategy:

    type: RollingUpdate

    rollingUpdate:

      maxSurge: 1

      maxUnavailable: 0

  template:

    metadata:

      labels:

        app: employee-portal-backend

    spec:

      serviceAccountName: backend-ksa

      containers:

        - name: backend

          image: us-central1-docker.pkg.dev/levin-495707/employee-portal/backend:latest

          imagePullPolicy: Always

          ports:

            - containerPort: 3001

          envFrom:

            - secretRef:

                name: backend-secret

          resources:

            requests:

              cpu: "100m"

              memory: "128Mi"

            limits:

              cpu: "500m"

              memory: "512Mi"

          livenessProbe:

            httpGet:

              path: /health

              port: 3001

            initialDelaySeconds: 30

            periodSeconds: 15

            failureThreshold: 3

          readinessProbe:

            httpGet:

              path: /ready

              port: 3001

            initialDelaySeconds: 10

            periodSeconds: 10

            failureThreshold: 3
 