apiVersion: v1

kind: ServiceAccount

metadata:

  name: backend-ksa

  namespace: employee-portal

  annotations:
iam.gke.io/gcp-service-account: employee-portal-backend-sa@levin-495707.iam.gserviceaccount.com
 